require("indent_blankline").setup {
  show_first_indent_level = true,
  filetype_exclude = {
    "help",
    "alpha",
    "dashboard",
    "neo-tree",
    "Trouble",
    "lazy",
    "mason",
    "notify",
    "toggleterm",
    "lazyterm",
  },
  buftype_exclude = { "terminal", "nofile" },
  show_trailing_blankline_indent = true,
  show_current_context = true,
  context_patterns = {
    "^if",
    "^table",
    "block",
    "class",
    "for",
    "function",
    "if_statement",
    "import",
    "list_literal",
    "method",
    "selector",
    "type",
    "var",
    "while",
  },
  space_char_blankline = " ",
}
